### ISSUE TITLE
Getting UNRESOLVED DEPENDENCIES

### ISSUE THREAD

**Issue by unoexperto** [felixmulder/sbt-dotty#1]
Could you please guide me why I'm getting these errors despite the fact I commented out scalaVersion  ?

Here is my build file

```
import com.typesafe.sbt.packager.docker.Cmd
import sbtassembly.MergeStrategy

lazy val commonSettings = Seq(
//  scalaVersion := "2.12.0-M5",
  organization := "com.zzz",
  version := "2.0"
)

lazy val root = (project in file(".")).
  enablePlugins(DockerPlugin, JavaAppPackaging, DependencyGraphPlugin, AssemblyPlugin, DottyPlugin).
  settings(commonSettings: _*).
  settings(
    name := "name",

    resolvers ++= Seq(
      "bintray mfglabs" at "https://dl.bintray.com/mfglabs/maven/"
    ),

    libraryDependencies ++= {
      val akkaV = "2.4.8"
      val scalaTestV = "3.0.0-RC4"
      Seq(
        "org.apache.httpcomponents" % "httpasyncclient" % "4.1.1",
        "com.typesafe.akka" %% "akka-actor" % akkaV,
        "com.typesafe.akka" %% "akka-stream" % akkaV withSources(),
        "com.typesafe.akka" %% "akka-http-core" % akkaV withSources(),
        "com.typesafe.akka" %% "akka-http-experimental" % akkaV withSources(),
        "com.typesafe.akka" %% "akka-http-spray-json-experimental" % akkaV withSources(),
        "com.ning" % "async-http-client" % "1.9.38",
        "org.apache.commons" % "commons-lang3" % "3.4" withSources(),
        "org.scalatest" %% "scalatest" % scalaTestV % "test",
        "org.jsoup" % "jsoup" % "1.9.2",
        "commons-io" % "commons-io" % "2.4",
        "commons-codec" % "commons-codec" % "1.10",
        "com.typesafe.scala-logging" %% "scala-logging" % "3.5.0-SNAPSHOT",
        "ch.qos.logback" % "logback-classic" % "1.1.+"
      )
    },

    scalacOptions ++= Seq("-unchecked", "-deprecation", "-encoding", "utf8", "-Xcheckinit"),
    mainClass in Compile := Some("com.zzz.Main"),
    fork := true, // Fork a new JVM for 'run' and 'test:run'
    javaOptions += "-Xmx2G", // Add a JVM option to use when forking a JVM for 'run'
    crossPaths := false,

    ivyLoggingLevel := UpdateLogging.Full, // Set Ivy logging to be at the highest level
    logLevel in compile := Level.Warn, // Only show warnings and errors on the screen for compilations. This applies to both test:compile and compile and is Info by default
    logLevel := Level.Warn, // Only show warnings and errors on the screen for all tasks (the default is Info). Individual tasks can then be more verbose using the previous setting
    persistLogLevel := Level.Debug, // Only store messages at info and above (the default is Debug). This is the logging level for replaying logging with 'last'
    traceLevel := 10, // Only show 10 lines of stack traces

    dockerBaseImage := "develar/java",
    dockerCommands := dockerCommands.value.flatMap {
      case cmd@Cmd("FROM", _) => List(cmd, Cmd("RUN", "apk update && apk add bash"))
      case other => List(other)
    },
    dockerRepository := Some("zzz"),
    version in Docker := version.value,

    assembleArtifact in assemblyPackageScala := false, // prevents sbt assembly from packaging dependencies into main jar
    assembleArtifact in assemblyPackageDependency := false, // prevents sbt assembly from packaging dependencies into main jar
    test in assembly := {},
    assemblyMergeStrategy in assembly := {
      case PathList("application.conf") => MergeStrategy.concat
      case x => MergeStrategy.defaultMergeStrategy(x)
    }
  )
```

errors I get are

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: ch.epfl.lamp#scala-library;0.1-SNAPSHOT: not found
[warn]  :: ch.epfl.lamp#scala-reflect;0.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      ch.epfl.lamp:scala-library:0.1-SNAPSHOT
[warn]        +- org.scala-lang.modules:scala-parser-combinators_2.11:1.0.4
[warn]        +- com.typesafe:ssl-config-core_2.11:0.2.1
[warn]        +- com.typesafe:ssl-config-akka_2.11:0.2.1
[warn]        +- com.typesafe.akka:akka-stream_2.11:2.4.8 (/home/expert/work/sideprojects/name/build.sbt#L21)
[warn]        +- com.typesafe.akka:akka-http-core_2.11:2.4.8 (/home/expert/work/sideprojects/name/build.sbt#L21)
[warn]        +- com.typesafe.akka:akka-http-experimental_2.11:2.4.8 (/home/expert/work/sideprojects/name/build.sbt#L21)
[warn]        +- com.typesafe.akka:akka-http-spray-json-experimental_2.11:2.4.8 (/home/expert/work/sideprojects/name/build.sbt#L21)
[warn]        +- com.zzz:name:2.0
[warn]      ch.epfl.lamp:scala-reflect:0.1-SNAPSHOT
[warn]        +- org.scalactic:scalactic_2.11:3.0.0-RC4
[warn]        +- org.scalatest:scalatest_2.11:3.0.0-RC4 (/home/expert/work/sideprojects/meal-momento/build.sbt#L21)
[warn]        +- com.zzz:meal-momento:2.0
sbt.ResolveException: unresolved dependency: ch.epfl.lamp#scala-library;0.1-SNAPSHOT: not found
unresolved dependency: ch.epfl.lamp#scala-reflect;0.1-SNAPSHOT: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
```

**Comment by felixmulder** [comment]
Looks like you're not resolving sonatype _snapshots_ correctly. Also - there is no "scala.reflect" published on our snapshots, so that would fail no matter what. Have a look at http://github.com/smarter/dotty-example-project if you would still like to try dotty with your project, as it contains a more detailed example.

**Comment by jvican** [comment]
Be careful and disable global and local sbt plugins since they will pull in scala dependencies. @cppexpert Maybe it would be good to write it down in the README.

**Comment by jvican** [comment]
Also, in your case, projects like `scalatest` are pulling in a lot of dependencies like scala reflect. You should try to either follow the resource than felix mentioned or remove tests and the dependency.

**Comment by MasseGuillaume** [comment]
it look like https://github.com/sbt/sbt/issues/2895 are you using sbt 0.13.13 ?
